# =================================================================
# TASK 1: Conduct comprehensive research and gather all sources.
# =================================================================
comprehensive_research_task:
  description: >
    Conduct a thorough investigation into the {topic}. 
    Start with a broad search to identify key themes and effective search terms, then perform a deep dive to find the most credible and relevant sources.
    Focus on academic papers, blogs, and reports that are highly relevant to the {topic}.
  expected_output: >
    An annotated bibliography of the top 10 sources. Each entry must include:
    - Title
    - A summary of its core findings that are relevant to {topic}. 
  agent: researcher

# =================================================================
# TASK 2: Analyze all research and create the core synthesis.
# =================================================================
synthesis_and_analysis_task:
  description: >
    Analyze the provided research sources to create a single, comprehensive synthesis document.
    This document should narrate the current state of knowledge on {topic}, highlighting key trends, significant discoveries, and any major gaps or controversies in the research.
    This synthesis is the foundation for the final report.
  expected_output: >
    A detailed synthesis report (approx. 800-1200 words) outlining:
    - The current state of research on {topic}.
    - Major findings and trends.
    - Key controversies or knowledge gaps.
  context:
    - comprehensive_research_task
  agent: researcher

# =================================================================
# TASK 3: Write the complete and final report.
# =================================================================
final_report_creation_task:
  description: >
    Using the research synthesis on {topic}, write a complete, polished, and professional final report.
    The report must be well-structured, clear, and easy for a non-specialist to understand.
    Incorporate all necessary sections including a title, introduction, findings, discussion, and conclusion.
    Format the entire document professionally and include a list of references in APA style at the end.
  expected_output: >
    A final, publication-ready report in a single Markdown file.
    The report must be fully formatted, grammatically perfect, and include a title page, a logical structure, and a complete reference list. Formatted as markdown without '```'

  context:
    - synthesis_and_analysis_task
  agent: reporting_analyst