research_task:
  description: >
    Conduct a thorough, in depth research using the tools available about the user query {topic}.
    You have two tools, a rag tool and a mcp server websearch tool.
    When using the websearch tool:
      - use `search_depth = "basic"` for simple questions
      - use `search_depth = "advanced"` for complex questions or when human feedback indicates to use advanced search.
    Gather, verify, and organize relevant information from the respective tool.
  expected_output: >
    Detailed information from the research findings.
  agent: research_agent

math_task:
  description: >
    Tackle mathematical problems of any complexity, from equations to proofs, from simple fundamental problems to complex mind boggling questions.
    Read and understand the user question: {topic}.
    Use the information provided by the research agent. Read this information thoroughly to solve user questions.
    Provide step by step reasoning, simplify concepts for better understanding, and deliver accurate solutions.
    Always format all mathematical expressions using LaTeX.
    Check with a human feedback before providing your final answer.
  expected_output: >
    A fully fledged solution, step by step written in detail for easy understanding.
    All math should be formatted in LaTeX.
    Formatted as markdown without '```'
  agent: math_agent